### PR TITLE
Adding sensors to CoRa

### PR DESCRIPTION
**Pull request by caguero**
Preliminary sensor integration. The sensor suite contains:

* A stereo camera.
* A 3D lidar.
* A GPS.
* An IMU.
* An acoustic sensor.

I also included an `rviz` config file and launch file.

vorc_sensors

How to visualize in `rviz`:

```
roslaunch vorc_gazebo marina.launch
roslaunch vorc_gazebo localization_example.launch
roslaunch vorc_gazebo rviz.launch
```

Note: The sensor location is preliminary, we can tweak it later.

### CODE REVIEW

**Comment by mabelzhang** [comment]
In the target branch, I did a slight refactoring of `cora.urdf.xacro` into `cora.xacro` in order to keep the inertial parameters in the repo for both v1 (requested) and v2 meshes. Could we move the sensor tags here into `cora.xacro` instead?

**Comment by caguero** [comment]
> In the target branch, I did a slight refactoring of `cora.urdf.xacro` into `cora.xacro` in order to keep the inertial parameters in the repo for both v1 (requested) and v2 meshes. Could we move the sensor tags here into `cora.xacro` instead?

Sure, moved in 0cab6d2.

**Comment by mabelzhang** [comment]
It could be a difference between colcon and catkin. I needed an additional install block in CMakeLists.txt for the rviz configuration to automatically load for me:
```
+# Install all the config files
+install(DIRECTORY config/
+  DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}/config)
```

~The point cloud is not being published for me. Is there some additional package I need to install?~
(Never mind, I just had to install `ros-melodic-velodyne-simulator` and `ros-melodic-hector-gazebo-plugins`. It's already in the VORC installation instructions, but I haven't created a Docker image using it... I probably should at some point - next week.)

Otherwise all the sensors are publishing for me. I can see the LIDAR and images in RViz.

**Comment by caguero** [comment]
> It could be a difference between colcon and catkin. I needed an additional install block in CMakeLists.txt for the rviz configuration to automatically load for me:
> 
> ```
> +# Install all the config files
> +install(DIRECTORY config/
> +  DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}/config)
> ```
> 
> ~The point cloud is not being published for me. Is there some additional package I need to install?~
> (Never mind, I just had to install `ros-melodic-velodyne-simulator` and `ros-melodic-hector-gazebo-plugins`. It's already in the VORC installation instructions, but I haven't created a Docker image using it... I probably should at some point - next week.)
> 
> Otherwise all the sensors are publishing for me. I can see the LIDAR and images in RViz.

Added in 8a15a63. This is good. It probably works for me because I'm not running `catkin make install`, just `catkin make`.

**Review by mabelzhang — APPROVED** [review]

**Comment by mabelzhang** [comment]
Feel free to merge

**Pull request merged**
