### PR TITLE
CoRa Model v.3 with Texture

### LINKED ISSUE #5: Tweak Cora mesh for more freeboard.
The stern section of the Cora vessel is to close to the water.  Recommend tweaking the mesh to move the bottom of the back section (the bottom of the pickup bed) roughly halfway up the vessel.  Crude attempt at recommended height of the back deck is attached.
stern

### PR DESCRIPTION
**Pull request by mabelzhang**
Design version 3 thanks to Rafi and Cole.
Fixes #5 with higher trunk bottom.
This PR also shifts sensors by z += 1 to account the offset added to `dummy_link`in #4.

The number of files changed is because I restructured the meshes directory a bit.

We might want to move some sensors. Currently the Velodyne is picking up all the mounts.

Screenshot from 2020-10-12 18-42-42_withSesors
Screenshot from 2020-10-12 18-50-34_stern
Screenshot from 2020-10-12 18-46-18

### CODE REVIEW

**Comment by bsb808** [comment]
Wow - that look slick!

**Review by caguero — APPROVED** [review]
It looks great!

**Comment by caguero** [comment]
One thing I've noticed is that if I send a thruster command, the propeller only spins for a second, and then, it stops.

**Comment by mabelzhang** [comment]
> One thing I've noticed is that if I send a thruster command, the propeller only spins for a second, and then, it stops.

Thanks for spotting that! This is only with `rostopic pub` right? The joystick still works. I wonder what is the difference.

Looks like that has been the case even in the initial PR. I can reproduce in hashes ab1b3a770a0dbfdb27bdfd8bc0f3065ac8a66dba and 735b5a5ac103f9b40ed85e1fb53becead0591c88

So looks like it's independent from this PR. I'm going to open an issue and unblock this PR.

**Comment by mabelzhang** [comment]
Issue opened. Let me know if you think this PR is clear to merge to unblock #13. Or we could wait till I fix the issue but that should probably be in a separate PR anyway to keep things clear.

**Comment by caguero** [comment]
> Issue opened. Let me know if you think this PR is clear to merge to unblock #13. Or we could wait till I fix the issue but that should probably be in a separate PR anyway to keep things clear.

Thanks! Let's merge!

**Pull request merged**
